### ISSUE TITLE
Installation on Zsh

### ISSUE THREAD

**Issue by aloysb** [pyronaur/zxb#3]
The installation does seem to work on a `zsh`.

Steps to reproduce:
 - Open a terminal with `zsh`
 - Install `zx`
 - Run the install script: `zx https://raw.githubusercontent.com/pyronaur/zxb/main/src/inc/install.mjs`
 - Reload the terminal
 
 The installation seems to fail. 

```
❯ zxb  
zsh: command not found: zxb
```

**Comment by aloysb** [comment]
The issue seems to be coming from here:

`if (process.args?._?.length === 1 && !process.args._[0].includes('zxb.mjs')) {` on the install scripts.

I am unsure what this guard is doing , but by commenting it out I successfully installed `zxb`.

I'd be happy to put a PR for this, but maybe someone has a better insight in that guard condition?

**Comment by pyronaur** [comment]
Hey! Thanks for letting me know.
I haven't checked what's going on there yet. zx seems to have switched how `argv` is handled a couple of times during the past few versions.

**Comment by aloysb** [comment]
Yeah, I was going to push a PR for the documentation, the 'tutorial' does
not work either (wrong indexing of `argv`).

Also, running `zxb lse` is not enough, you have to do `zxb create lse`.
Might be related to the same issue.

Pretty neat project though, a very good idea.

**Comment by pyronaur** [comment]
Thanks!

Fixed the install issue: https://github.com/pyronaur/zxb/commit/a58ca0f04b2d770c368984dcbe595e7912254d39

What OS are you running? `zxb lse` works on my mac, but doesn't work on Ubuntu, so I think something might be up there.

**Comment by aloysb** [comment]
Hm interesting, yes that's from Ubuntu. I can try to have a peek at it and
if I see anything I'll let you know

**Comment by pyronaur** [comment]
Oh, Ubuntu isn't to blame, after all, reproduced on mac as well. Looking...

**Comment by aloysb** [comment]
It seems to be around line 63 on the main file.

I'm just on my phone right now so hard to debug, you have a condition:

`if(input && !action)`

Probably another issue with the indexing of argv?

**Comment by aloysb** [comment]
Yes I can't test but I'd say `input` returns `undefined` because of the argv indexing.. it's looking at index `1`, not `0`.

But again, from my mobile so this is untested!

**Comment by pyronaur** [comment]
Yeah, the indexes were off because zx changed that in v7, and I got confused along the way with my messy dev environment (I've got the git project symlinked and after testing updates forgot to re-link)

I've updated zxb to v1.0.5 now. `zxb update` should do the trick, if it doesn't, just run the install script again.
